import { StyleSheet } from "react-native";

export const colors = {
  veryPery: "#6768ab",
  veryPeryLight: "#6a67ad59",
};

export const styles = StyleSheet.create({
  mainTitle: {
    backgroundColor: colors.veryPery,
    color: "white",
    paddingTop: 35,
    textAlign: "center",
  },
  modifierContainer: {
    paddingLeft: 24,
    paddingRight: 24,
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    backgroundColor: colors.veryPeryLight,
  },
  createNewContainer: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "flex-end",
    backgroundColor: "#aabbcc",
    height: 59,
  },
  createNewText: {
    marginTop: 18,
    marginRight: 10,
    marginBottom: -20,
    width: "80%",
  },
  header: {
    fontSize: 14,
    fontWeight: "bold",
    textAlign: "center",
  },
  inputTextLabel: {
    marginTop: 12,
    fontSize: 14,
    fontWeight: "bold",
    textAlign: "center",
  },
  toggleTextLabel: {
    margin: 24,
    marginBottom: 0,
    fontSize: 14,
    fontWeight: "bold",
    textAlign: "left",
  },
  button_container: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  button: {
    margin: 5,
    backgroundColor: colors.veryPery,
    padding: 10,
    borderRadius: 5,
    width: 150,
  },
  disabledBtn: {
    color: "#fff",
    fontWeight: "bold",
    textAlign: "center",
    opacity: 0.3,
  },
  button_text: {
    color: "#fff",
    fontWeight: "bold",
    textAlign: "center",
  },
  text_and_input_Name: {
    height: 100,
    width: 300,
    backgroundColor: "white",
    borderColor: colors.veryPery,
    borderWidth: 2,
    paddingLeft: 5,
    textAlignVertical: "top",
    borderRadius: 4,
  },
  timeLinePoint: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    paddingTop: 3,
    width: "100%",
  },
  timeLineDateColumn: {
    color: "white",
    display: "flex",
    flexDirection: "column",
    backgroundColor: colors.veryPery,
    borderRadius: 4,
    width: 110,
    padding: 5,
  },
  timePointRightSide: {
    paddingTop: 16,
    paddingLeft: 10,
    margin: 5,
    borderLeftWidth: 4,
    borderLeftColor: colors.veryPery,
  }, // 0 1 2 3 4 5 6 7 8 9 A 0 1 2 3 4 5 6 7 8 9 B 0 1 2 3 4 5 6 7 8 9 C
  name_icon_line: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 16,
  },
  nameText: {
    color: colors.veryPery,
    width: 200,
    padding: 5,
  },
  roundDot_red: {
    marginLeft: -18,
    marginTop: -19,
    width: 12,
    height: 12,
    borderRadius: 6,
    backgroundColor: "red",
  },
  roundDot_green: {
    marginLeft: -18,
    marginTop: -19,
    width: 12,
    height: 12,
    borderRadius: 6,
    backgroundColor: "green",
  },
  balanceText_green: {
    color: "green",
    marginTop: -10,
    marginBottom: 20,
  },
  balanceText_red: {
    color: "red",
    marginTop: -10,
    marginBottom: 20,
  },
  balanceText_white: {
    color: "white",
    marginTop: -10,
    marginBottom: 20,
  },
  amountLabel_red: {
    color: "red",
    marginTop: -10,
    marginBottom: 20,
  },
  amountLabel_green: {
    color: "green",
    marginTop: -10,
    marginBottom: 20,
  },
  roundDot_white: {
    marginLeft: -18,
    marginTop: -19,
    width: 12,
    height: 12,
    borderRadius: 6,
    backgroundColor: "white",
  },
  text_and_input_Start: {
    height: 40,
    width: 300,
    backgroundColor: "white",
    borderColor: colors.veryPery,
    borderWidth: 2,
    paddingLeft: 5,
    textAlign: "center",
    borderRadius: 4,
  },
  switcherLine: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginTop: 5,
  },
  switcherLabel: {
    width: "50%",
  },
  text_and_input_Amount: {
    height: 40,
    width: 300,
    backgroundColor: "white",
    borderColor: colors.veryPery,
    borderWidth: 2,
    paddingLeft: 5,
    borderRadius: 4,
  },
  text_and_input: {
    height: 40,
    width: 210,
    backgroundColor: "white",
    borderColor: colors.veryPery,
    borderWidth: 2,
    paddingLeft: 5,
    borderRadius: 4,
    textAlign: "center",
  },
  periodicalBox: {
    backgroundColor: colors.veryPery,
    padding: 15,
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
  },
  labelStyle: {
    color: "black",
    fontWeight: "900",
  },
  labelDate: {
    padding: 12,
    margin: 12,
    width: "100%",
    fontWeight: "900",
    backgroundColor: colors.veryPery,
    color: "white",
    borderRadius: 4,
    textAlign: "center",
  },
  timeLineContainer: {
    marginTop: 0,
    paddingTop: 10,
  },
  timeLineDate: {
    color: "white",
    paddingRight: 5,
    textAlign: "right",
  },
  required_asterix: {
    color: "red",
  },
  editIcon: {
    marginRight: 15,
  },
  modalWhiteCentered: {
    flexDirection: "column",
    height: 300,
    display: "flex",
    alignItems: "center",
  },
  input_Date: {
    textAlign: "center",
  },
  dd_mm_yyyy_inputRow: {
    flex: 1,
    flexDirection: "row",
    zIndex: 100,
  },
  dd_mm_inputColumn: {
    margin: 1,
    width: 110,
    height: 65,
    backgroundColor: "white",
    borderRadius: 4,
    borderColor: colors.veryPery,
  },
  dd_mm_inputColumn_warning: {
    margin: 1,
    width: 110,
    height: 65,
    backgroundColor: "red",
    borderRadius: 4,
    borderColor: colors.veryPery,
  },
  yyyy_inputColumn: {
    margin: 1,
    width: 130,
    height: 65,
    backgroundColor: "white",
    borderRadius: 4,
    borderColor: colors.veryPery,
  },
  yyyy_inputColumn_warning: {
    margin: 1,
    width: 130,
    height: 65,
    backgroundColor: "red",
    borderRadius: 4,
    borderColor: colors.veryPery,
  },
});
